name: py35
dependencies:
- pip=8.1.1=py35_0
- python=3.5.1=0
- setuptools=20.3=py35_0
- wheel=0.29.0=py35_0
- pip:
  - aiohttp==0.18.4
  - chardet==2.3.0
  - furl==0.4.2
  - humanfriendly==2.1
  - invoke==0.11.1
  - mako==1.0.1
  - raven==5.27.0
  - stevedore==1.2.0
  - tornado==4.3
  - git+https://github.com/CenterForOpenScience/waterbutler.git@0.19.0#egg=waterbutler
  - agent==0.1.2
  - Pygments==2.0.2
  - pydocx==0.7.0
  - Pillow==2.8.2
  - nbconvert==4.2.0
  - nbformat==4.1.0
  - traitlets==4.2.2
  - jsonschema==2.4.0
  - jinja2==2.7.3
  - mistune==0.7
  - docutils==0.12
  - pandas==0.17.1
  - git+https://github.com/icereval/xlrd.git
  - markdown==2.6.2
  - certifi==2015.4.28
